Fix two design issues in the test-suite.
1. the test "bdc90417" wasn't run [correctly]; and

2. don't use test filenames as .PHONY targets.

diff --git a/tests/GNUmakefile b/tests/GNUmakefile
--- a/tests/GNUmakefile
+++ b/tests/GNUmakefile
@@ -2,46 +2,38 @@ ROOTFS = ./rootfs
 PROOT  = ../src/proot
 CC     = gcc
 
-TESTS_SH  = $(wildcard test-*.sh)
-TESTS_C   = $(wildcard test-*.c)
-TESTS_ALL = $(TESTS_SH) $(TESTS_C)
+CHECK_TESTS = $(patsubst %,check-%, $(wildcard test-*.sh) $(wildcard test-*.c))
 
-test check: | clean_failure check_failure
+.PHONY: check clean_failure check_failure setup check-%
+
+check: | clean_failure check_failure
 
 clean_failure:
 	@rm -f failure
 
-check_failure: $(TESTS_ALL)
+check_failure: $(CHECK_TESTS)
 	@bash -c '! test -e failure'
 
-.PHONY: test check clean_failure check_failure setup test-%.sh test-%.c
+check-%.sh: %.sh setup
+	$(Q)env PROOT=$(PROOT) ROOTFS=$(ROOTFS) sh -e $< $(silently); $(call check,$*)
 
-test-%.sh: setup
-	$(Q)env PROOT=$(PROOT) ROOTFS=$(ROOTFS) sh -e $@ $(silently); $(CHECK)
+check-%.c: $(ROOTFS)/bin/% setup
+	$(call check_c,$*,$(PROOT) -b /proc $(ROOTFS) /bin/$*)
 
-.SECONDARY: $(patsubst %.c,,$(TESTS_C))
-test-%.c: setup $(ROOTFS)/bin/test-%
-	$(Q)if [ -e $(ROOTFS)/bin/test-$* ]; then	\
-		$(PROOT) -b /proc $(ROOTFS) /bin/test-$* $(silently); $(CHECK) \
+# Special case.
+check-test-bdc90417.c: test-bdc90417
+	$(call check_c,$<,$(PROOT) -w . / $<)
+
+check_c = $(Q)if [ -e $< ]; then			\
+		$(2) $(silently); $(call check,$(1))	\
 	else						\
-		echo "  TEST	$* skipped";		\
+		echo "  CHECK	$(1) skipped";		\
 	fi
 
-# Very special test.
-test-bdc90417:
-	$(Q)$(CC) $@.c -o $@ $(silently) || true
-
-test-bdc90417.c: test-bdc90417
-	$(Q)if [ -e $< ]; then			\
-		$(PROOT) / $< ; $(CHECK)	\
-	else					\
-		echo "  TEST	$* skipped";	\
-	fi
-
-CHECK = case "$$?" in					\
-		0)   echo "  TEST	$* ok";;	\
-		125) echo "  TEST	$* skipped";;	\
-		*)   echo "  TEST	$* FAILED";	\
+check = case "$$?" in					\
+		0)   echo "  CHECK	$(1) ok";;	\
+		125) echo "  CHECK	$(1) skipped";;	\
+		*)   echo "  CHECK	$(1) FAILED";	\
 		     touch failure ;;			\
 	esac
 
@@ -58,9 +50,14 @@ $(ROOTFS)/bin/abs-true:
 $(ROOTFS)/bin/rel-true:
 	@ln -fs ./true $@
 
-$(ROOTFS)/bin/%: # %.c
+.SECONDARY: $(patsubst %.c,$(ROOTFS)/bin/%, $(wildcard test-*.c))
+$(ROOTFS)/bin/%: %.c
 	@test -e $(dir $@) || mkdir -p $(dir $@)
 	$(Q)$(CC) -static $*.c -o $@ $(silently) || true
+
+# Special case.
+test-bdc90417: test-bdc90417.c
+	$(Q)$(CC) $< -o $@ $(silently) || true
 
 ######################################################################
 # Beautified output
